defaults:
  - system: pretrain_ply
  - data: pretrain_ply
  - logger: [wandb]
  - callback: pretrain
  - trainer: default
  - hydra: default
  - _self_           

# Global settings
project_name: "3DMorphCell"
seed: 42