_target_: morphcell.model.CytoDLPointReconstructor
latent_dim: 512
num_output_points: 2025
hidden_dim: 64
hidden_conv2d_channels: [64, 64, 64, 64]
hidden_conv1d_channels: [512, 512]
hidden_decoder_dim: 512
k: 20
mode: vector
include_cross: true
include_coords: true
symmetry_breaking_axis: null
grid_shape: plane
grid_std: 0.3
sphere_path: null
gaussian_path: null
